apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devops-app-ingress
  namespace: production
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - app.devops.example.com
      secretName: devops-app-tls
  rules:
    - host: app.devops.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: devops-app-service
                port:
                  number: 80